from __future__ import annotations

import json
from pathlib import Path
from textwrap import dedent

ROOT = Path.cwd()


def write(path: str, content: str) -> None:
    target = ROOT / path
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(dedent(content).lstrip(), encoding="utf-8")


def read_json(path: str) -> dict:
    return json.loads((ROOT / path).read_text(encoding="utf-8"))


def write_json(path: str, value: dict) -> None:
    write(path, json.dumps(value, indent=2) + "\n")


# Domain generated by the Phase 3 generator, then completed as the canonical example.
write(
    "packages/backend/agent-task/src/lib/domain/agent-task.ts",
    r'''
    export const agentTaskStatuses = ['queued', 'running', 'completed', 'failed'] as const;
    export type AgentTaskStatus = (typeof agentTaskStatuses)[number];

    export interface AgentTask {
      readonly id: string;
      readonly ownerId: string;
      readonly title: string;
      readonly prompt: string;
      readonly status: AgentTaskStatus;
      readonly correlationId: string;
      readonly createdAt: Date;
    }

    export interface CreateAgentTaskInput {
      readonly id: string;
      readonly ownerId: string;
      readonly title: string;
      readonly prompt: string;
      readonly correlationId: string;
      readonly createdAt: Date;
    }

    export class AgentTaskValidationError extends Error {
      public constructor(message: string) {
        super(message);
        this.name = 'AgentTaskValidationError';
      }
    }

    function requiredText(value: unknown, field: string, maximum: number): string {
      if (typeof value !== 'string') {
        throw new AgentTaskValidationError(`${field} is required.`);
      }
      const normalized = value.trim();
      if (normalized.length === 0) {
        throw new AgentTaskValidationError(`${field} is required.`);
      }
      if (normalized.length > maximum) {
        throw new AgentTaskValidationError(
          `${field} must be at most ${maximum} characters.`,
        );
      }
      return normalized;
    }

    export function createAgentTask(input: CreateAgentTaskInput): AgentTask {
      return {
        id: requiredText(input.id, 'id', 128),
        ownerId: requiredText(input.ownerId, 'ownerId', 128),
        title: requiredText(input.title, 'title', 120),
        prompt: requiredText(input.prompt, 'prompt', 4000),
        status: 'queued',
        correlationId: requiredText(input.correlationId, 'correlationId', 128),
        createdAt: input.createdAt,
      };
    }
    ''',
)
write(
    "packages/backend/agent-task/src/lib/application/agent-task-repository.ts",
    r'''
    import type { AgentTaskExecutionRequested } from '@agentic-webapp/contracts';

    import type { AgentTask } from '../domain/agent-task';

    export const AGENT_TASK_REPOSITORY = Symbol('AGENT_TASK_REPOSITORY');

    export interface AgentTaskRepository {
      create(
        task: AgentTask,
        executionRequested: AgentTaskExecutionRequested,
      ): Promise<void>;
      findById(id: string): Promise<AgentTask | null>;
    }
    ''',
)
write(
    "packages/backend/agent-task/src/lib/application/create-agent-task.ts",
    r'''
    import { randomUUID } from 'node:crypto';

    import {
      agentTaskExecutionRequestedSchema,
      type AgentTaskExecutionRequested,
    } from '@agentic-webapp/contracts';

    import {
      createAgentTask,
      type AgentTask,
    } from '../domain/agent-task';
    import type { AgentTaskRepository } from './agent-task-repository';

    export interface CreateAgentTaskCommand {
      readonly actorId: string;
      readonly title: string;
      readonly prompt: string;
      readonly correlationId?: string;
    }

    export interface AgentTaskDependencies {
      readonly createId: () => string;
      readonly now: () => Date;
    }

    const defaultDependencies: AgentTaskDependencies = {
      createId: randomUUID,
      now: () => new Date(),
    };

    export class CreateAgentTask {
      public constructor(
        private readonly repository: AgentTaskRepository,
        private readonly dependencies: AgentTaskDependencies = defaultDependencies,
      ) {}

      public async execute(command: CreateAgentTaskCommand): Promise<AgentTask> {
        const createdAt = this.dependencies.now();
        const task = createAgentTask({
          id: this.dependencies.createId(),
          ownerId: command.actorId,
          title: command.title,
          prompt: command.prompt,
          correlationId: command.correlationId ?? this.dependencies.createId(),
          createdAt,
        });
        const executionRequested: AgentTaskExecutionRequested =
          agentTaskExecutionRequestedSchema.parse({
            version: 1,
            taskId: task.id,
            actorId: task.ownerId,
            prompt: task.prompt,
            correlationId: task.correlationId,
            occurredAt: task.createdAt.toISOString(),
          });

        await this.repository.create(task, executionRequested);
        return task;
      }
    }
    ''',
)
write(
    "packages/backend/agent-task/src/lib/application/get-agent-task.ts",
    r'''
    import type { AgentTask } from '../domain/agent-task';
    import type { AgentTaskRepository } from './agent-task-repository';

    export class AgentTaskNotFoundError extends Error {
      public constructor(id: string) {
        super(`Agent task ${id} was not found.`);
        this.name = 'AgentTaskNotFoundError';
      }
    }

    export class AgentTaskForbiddenError extends Error {
      public constructor() {
        super('The actor cannot access this agent task.');
        this.name = 'AgentTaskForbiddenError';
      }
    }

    export class GetAgentTask {
      public constructor(private readonly repository: AgentTaskRepository) {}

      public async execute(id: string, actorId: string): Promise<AgentTask> {
        const task = await this.repository.findById(id);
        if (!task) {
          throw new AgentTaskNotFoundError(id);
        }
        if (task.ownerId !== actorId) {
          throw new AgentTaskForbiddenError();
        }
        return task;
      }
    }
    ''',
)
write(
    "packages/backend/agent-task/src/lib/application/create-agent-task.spec.ts",
    r'''
    import { describe, expect, it, vi } from 'vitest';

    import { CreateAgentTask } from './create-agent-task';

    describe('CreateAgentTask', () => {
      it('validates, persists, and schedules a correlated execution request', async () => {
        const create = vi.fn().mockResolvedValue(undefined);
        const useCase = new CreateAgentTask(
          { create, findById: vi.fn() },
          {
            createId: vi
              .fn()
              .mockReturnValueOnce('11111111-1111-4111-8111-111111111111')
              .mockReturnValueOnce('22222222-2222-4222-8222-222222222222'),
            now: () => new Date('2026-07-31T17:00:00.000Z'),
          },
        );

        const result = await useCase.execute({
          actorId: '33333333-3333-4333-8333-333333333333',
          title: '  Summarize customer feedback  ',
          prompt: '  Group the feedback into themes.  ',
        });

        expect(result).toMatchObject({
          title: 'Summarize customer feedback',
          prompt: 'Group the feedback into themes.',
          status: 'queued',
          correlationId: '22222222-2222-4222-8222-222222222222',
        });
        expect(create).toHaveBeenCalledWith(
          result,
          expect.objectContaining({
            taskId: result.id,
            correlationId: result.correlationId,
            version: 1,
          }),
        );
      });

      it('rejects blank prompts before persistence', async () => {
        const create = vi.fn();
        const useCase = new CreateAgentTask(
          { create, findById: vi.fn() },
          { createId: () => 'id', now: () => new Date() },
        );

        await expect(
          useCase.execute({ actorId: 'actor', title: 'Title', prompt: '   ' }),
        ).rejects.toThrow('prompt is required');
        expect(create).not.toHaveBeenCalled();
      });
    });
    ''',
)
write(
    "packages/backend/agent-task/src/lib/application/get-agent-task.spec.ts",
    r'''
    import { describe, expect, it, vi } from 'vitest';

    import { GetAgentTask } from './get-agent-task';

    const task = {
      id: 'task-id',
      ownerId: 'owner-id',
      title: 'Task',
      prompt: 'Prompt',
      status: 'queued' as const,
      correlationId: 'correlation-id',
      createdAt: new Date('2026-07-31T17:00:00.000Z'),
    };

    describe('GetAgentTask', () => {
      it('returns an owned task', async () => {
        const useCase = new GetAgentTask({
          create: vi.fn(),
          findById: vi.fn().mockResolvedValue(task),
        });
        await expect(useCase.execute(task.id, task.ownerId)).resolves.toEqual(task);
      });

      it('rejects access by another actor', async () => {
        const useCase = new GetAgentTask({
          create: vi.fn(),
          findById: vi.fn().mockResolvedValue(task),
        });
        await expect(useCase.execute(task.id, 'other-actor')).rejects.toThrow(
          'cannot access',
        );
      });
    });
    ''',
)
write(
    "packages/backend/agent-task/src/index.ts",
    r'''
    export * from './lib/application/agent-task-repository';
    export * from './lib/application/create-agent-task';
    export * from './lib/application/get-agent-task';
    export * from './lib/domain/agent-task';
    ''',
)
write(
    "packages/backend/agent-task/README.md",
    r'''
    # Agent Task domain

    Canonical reference domain for the template. It owns task validation, actor-scoped reads, execution-request creation, and persistence ports. NestJS, Drizzle, HTTP, and queue transports remain adapters outside this project.
    ''',
)

# Shared event contract generated by Phase 3 and consumed by domain, database, and worker.
write(
    "packages/contracts/src/agent-task-execution-requested/schema.ts",
    r'''
    import { z } from 'zod';

    export const agentTaskExecutionRequestedSchema = z.object({
      version: z.literal(1),
      taskId: z.string().uuid(),
      actorId: z.string().min(1),
      prompt: z.string().min(1).max(4000),
      correlationId: z.string().min(1),
      occurredAt: z.string().datetime(),
    });

    export type AgentTaskExecutionRequested = z.infer<
      typeof agentTaskExecutionRequestedSchema
    >;
    ''',
)
write(
    "packages/contracts/src/agent-task-execution-requested/schema.spec.ts",
    r'''
    import { describe, expect, it } from 'vitest';

    import { agentTaskExecutionRequestedSchema } from './schema';

    describe('agentTaskExecutionRequestedSchema', () => {
      it('preserves the versioned task and correlation identifiers', () => {
        const result = agentTaskExecutionRequestedSchema.parse({
          version: 1,
          taskId: '11111111-1111-4111-8111-111111111111',
          actorId: 'actor-1',
          prompt: 'Summarize the document.',
          correlationId: 'trace-1',
          occurredAt: '2026-07-31T17:00:00.000Z',
        });
        expect(result).toMatchObject({ version: 1, correlationId: 'trace-1' });
      });
    });
    ''',
)

# Canonical HTTP source.
openapi = read_json("packages/contracts/openapi/source/openapi.json")
openapi["info"]["version"] = "0.2.0"
openapi["tags"].append(
    {
        "name": "agent-tasks",
        "description": "Actor-scoped tasks queued for agent execution.",
    }
)
openapi["paths"]["/api/agent-tasks"] = {
    "post": {
        "operationId": "createAgentTask",
        "summary": "Create an agent task",
        "tags": ["agent-tasks"],
        "parameters": [
            {"$ref": "#/components/parameters/ActorId"},
            {"$ref": "#/components/parameters/CorrelationId"},
        ],
        "requestBody": {
            "required": True,
            "content": {
                "application/json": {
                    "schema": {"$ref": "#/components/schemas/CreateAgentTaskRequest"}
                }
            },
        },
        "responses": {
            "201": {
                "description": "The task was validated and queued.",
                "content": {
                    "application/json": {
                        "schema": {"$ref": "#/components/schemas/AgentTaskResponse"}
                    }
                },
            },
            "400": {
                "description": "The request was invalid.",
                "content": {
                    "application/json": {
                        "schema": {"$ref": "#/components/schemas/ErrorResponse"}
                    }
                },
            },
        },
    }
}
openapi["paths"]["/api/agent-tasks/{taskId}"] = {
    "get": {
        "operationId": "getAgentTask",
        "summary": "Read an owned agent task",
        "tags": ["agent-tasks"],
        "parameters": [
            {
                "name": "taskId",
                "in": "path",
                "required": True,
                "schema": {"type": "string", "format": "uuid"},
            },
            {"$ref": "#/components/parameters/ActorId"},
            {"$ref": "#/components/parameters/CorrelationId"},
        ],
        "responses": {
            "200": {
                "description": "The owned task.",
                "content": {
                    "application/json": {
                        "schema": {"$ref": "#/components/schemas/AgentTaskResponse"}
                    }
                },
            },
            "403": {
                "description": "The task belongs to another actor.",
                "content": {
                    "application/json": {
                        "schema": {"$ref": "#/components/schemas/ErrorResponse"}
                    }
                },
            },
            "404": {
                "description": "The task does not exist.",
                "content": {
                    "application/json": {
                        "schema": {"$ref": "#/components/schemas/ErrorResponse"}
                    }
                },
            },
        },
    }
}
components = openapi.setdefault("components", {})
components["parameters"] = {
    "ActorId": {
        "name": "x-actor-id",
        "in": "header",
        "required": True,
        "description": "Development actor context. Phase 8 replaces this adapter with authenticated identity.",
        "schema": {"type": "string", "minLength": 1},
    },
    "CorrelationId": {
        "name": "x-correlation-id",
        "in": "header",
        "required": False,
        "description": "Optional caller correlation identifier propagated into persistence and jobs.",
        "schema": {"type": "string", "minLength": 1},
    },
}
components["schemas"].update(
    {
        "CreateAgentTaskRequest": {"$ref": "./schemas/create-agent-task-request.json"},
        "AgentTaskResponse": {"$ref": "./schemas/agent-task-response.json"},
        "ErrorResponse": {"$ref": "./schemas/error-response.json"},
    }
)
write_json("packages/contracts/openapi/source/openapi.json", openapi)
write_json(
    "packages/contracts/openapi/source/schemas/create-agent-task-request.json",
    {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "type": "object",
        "additionalProperties": False,
        "required": ["title", "prompt"],
        "properties": {
            "title": {"type": "string", "minLength": 1, "maxLength": 120},
            "prompt": {"type": "string", "minLength": 1, "maxLength": 4000},
        },
    },
)
write_json(
    "packages/contracts/openapi/source/schemas/agent-task-response.json",
    {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "type": "object",
        "additionalProperties": False,
        "required": ["id", "title", "prompt", "status", "correlationId", "createdAt"],
        "properties": {
            "id": {"type": "string", "format": "uuid"},
            "title": {"type": "string"},
            "prompt": {"type": "string"},
            "status": {"type": "string", "enum": ["queued", "running", "completed", "failed"]},
            "correlationId": {"type": "string"},
            "createdAt": {"type": "string", "format": "date-time"},
        },
    },
)
write_json(
    "packages/contracts/openapi/source/schemas/error-response.json",
    {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "type": "object",
        "additionalProperties": False,
        "required": ["code", "message"],
        "properties": {
            "code": {"type": "string"},
            "message": {"type": "string"},
        },
    },
)

# Drizzle schema, repository adapter, outbox, and reversible migration.
write(
    "packages/database/src/schema/agent-task.ts",
    r'''
    import type { AgentTaskExecutionRequested } from '@agentic-webapp/contracts';
    import { jsonb, text, timestamp, uuid, varchar } from 'drizzle-orm/pg-core';

    import { appSchema } from './platform';

    export const agentTasks = appSchema.table('agent_tasks', {
      id: uuid('id').primaryKey(),
      ownerId: text('owner_id').notNull(),
      title: varchar('title', { length: 120 }).notNull(),
      prompt: text('prompt').notNull(),
      status: varchar('status', { length: 32 }).notNull(),
      correlationId: text('correlation_id').notNull(),
      createdAt: timestamp('created_at', { mode: 'date', withTimezone: true })
        .notNull()
        .defaultNow(),
    });

    export const jobOutbox = appSchema.table('job_outbox', {
      id: uuid('id').primaryKey(),
      kind: text('kind').notNull(),
      payload: jsonb('payload').$type<AgentTaskExecutionRequested>().notNull(),
      correlationId: text('correlation_id').notNull(),
      createdAt: timestamp('created_at', { mode: 'date', withTimezone: true })
        .notNull()
        .defaultNow(),
      processedAt: timestamp('processed_at', { mode: 'date', withTimezone: true }),
    });

    export type AgentTaskRow = typeof agentTasks.$inferSelect;
    export type JobOutboxRow = typeof jobOutbox.$inferSelect;
    ''',
)
write(
    "packages/database/src/adapters/agent-task-repository.ts",
    r'''
    import { randomUUID } from 'node:crypto';

    import type {
      AgentTask,
      AgentTaskRepository,
      AgentTaskStatus,
    } from '@agentic-webapp/backend-agent-task';
    import {
      agentTaskExecutionRequestedSchema,
      type AgentTaskExecutionRequested,
    } from '@agentic-webapp/contracts';
    import { eq } from 'drizzle-orm';

    import type { Database } from '../client';
    import { agentTasks, jobOutbox } from '../schema';

    export class DrizzleAgentTaskRepository implements AgentTaskRepository {
      public constructor(private readonly database: Database) {}

      public async create(
        task: AgentTask,
        executionRequested: AgentTaskExecutionRequested,
      ): Promise<void> {
        const payload = agentTaskExecutionRequestedSchema.parse(executionRequested);
        await this.database.transaction(async (transaction) => {
          await transaction.insert(agentTasks).values({
            id: task.id,
            ownerId: task.ownerId,
            title: task.title,
            prompt: task.prompt,
            status: task.status,
            correlationId: task.correlationId,
            createdAt: task.createdAt,
          });
          await transaction.insert(jobOutbox).values({
            id: randomUUID(),
            kind: 'agent-task.execute.v1',
            payload,
            correlationId: payload.correlationId,
            createdAt: task.createdAt,
          });
        });
      }

      public async findById(id: string): Promise<AgentTask | null> {
        const [row] = await this.database
          .select()
          .from(agentTasks)
          .where(eq(agentTasks.id, id))
          .limit(1);
        if (!row) {
          return null;
        }
        return {
          id: row.id,
          ownerId: row.ownerId,
          title: row.title,
          prompt: row.prompt,
          status: row.status as AgentTaskStatus,
          correlationId: row.correlationId,
          createdAt: row.createdAt,
        };
      }
    }
    ''',
)
write(
    "packages/database/migrations/20260731140200000_add_agent_tasks.ts",
    r'''
    import type { MigrationBuilder } from 'node-pg-migrate';

    const tasks = { schema: 'app', name: 'agent_tasks' } as const;
    const outbox = { schema: 'app', name: 'job_outbox' } as const;

    export async function up(pgm: MigrationBuilder): Promise<void> {
      pgm.createTable(tasks, {
        id: { type: 'uuid', primaryKey: true },
        owner_id: { type: 'text', notNull: true },
        title: { type: 'varchar(120)', notNull: true },
        prompt: { type: 'text', notNull: true },
        status: { type: 'varchar(32)', notNull: true },
        correlation_id: { type: 'text', notNull: true },
        created_at: {
          type: 'timestamptz',
          notNull: true,
          default: pgm.func('current_timestamp'),
        },
      });
      pgm.addConstraint(tasks, 'agent_tasks_status_check', {
        check: "status in ('queued', 'running', 'completed', 'failed')",
      });
      pgm.createIndex(tasks, ['owner_id', 'created_at']);

      pgm.createTable(outbox, {
        id: { type: 'uuid', primaryKey: true },
        kind: { type: 'text', notNull: true },
        payload: { type: 'jsonb', notNull: true },
        correlation_id: { type: 'text', notNull: true },
        created_at: {
          type: 'timestamptz',
          notNull: true,
          default: pgm.func('current_timestamp'),
        },
        processed_at: { type: 'timestamptz' },
      });
      pgm.createIndex(outbox, ['processed_at', 'created_at']);
      pgm.createIndex(outbox, 'correlation_id');
    }

    export async function down(pgm: MigrationBuilder): Promise<void> {
      pgm.dropTable(outbox, { ifExists: true });
      pgm.dropTable(tasks, { ifExists: true });
    }
    ''',
)
write(
    "packages/database/src/adapters/agent-task-repository.integration.test.ts",
    r'''
    import { CreateAgentTask, GetAgentTask } from '@agentic-webapp/backend-agent-task';
    import { PostgreSqlContainer } from '@testcontainers/postgresql';
    import { afterAll, beforeAll, describe, expect, it } from 'vitest';

    import { DrizzleAgentTaskRepository } from './agent-task-repository';
    import { createDatabase, type DatabaseConnection } from '../client';
    import { runMigrations } from '../migrations';
    import { jobOutbox } from '../schema';

    describe('DrizzleAgentTaskRepository', () => {
      let connection: DatabaseConnection;
      let stop: (() => Promise<void>) | undefined;

      beforeAll(async () => {
        const container = await new PostgreSqlContainer('postgres:17-alpine')
          .withDatabase('app')
          .withUsername('postgres')
          .withPassword('postgres')
          .start();
        stop = () => container.stop();
        await runMigrations({ connectionString: container.getConnectionUri() });
        connection = createDatabase({
          connectionString: container.getConnectionUri(),
          maxConnections: 2,
        });
      });

      afterAll(async () => {
        await connection?.close();
        await stop?.();
      });

      it('persists the task and execution request atomically and enforces ownership', async () => {
        const repository = new DrizzleAgentTaskRepository(connection.database);
        const createTask = new CreateAgentTask(repository, {
          createId: (() => {
            const ids = [
              '11111111-1111-4111-8111-111111111111',
              '22222222-2222-4222-8222-222222222222',
            ];
            return () => ids.shift() ?? '33333333-3333-4333-8333-333333333333';
          })(),
          now: () => new Date('2026-07-31T17:00:00.000Z'),
        });
        const task = await createTask.execute({
          actorId: 'actor-1',
          title: 'Analyze incidents',
          prompt: 'Summarize common root causes.',
        });

        const loaded = await new GetAgentTask(repository).execute(task.id, 'actor-1');
        expect(loaded).toEqual(task);
        await expect(
          new GetAgentTask(repository).execute(task.id, 'actor-2'),
        ).rejects.toThrow('cannot access');

        const outbox = await connection.database.select().from(jobOutbox);
        expect(outbox).toHaveLength(1);
        expect(outbox[0]).toMatchObject({
          kind: 'agent-task.execute.v1',
          correlationId: task.correlationId,
          payload: expect.objectContaining({ taskId: task.id }),
        });
      });
    });
    ''',
)

schema_index = (ROOT / "packages/database/src/schema/index.ts").read_text(encoding="utf-8")
if "./agent-task" not in schema_index:
    write("packages/database/src/schema/index.ts", schema_index + "export * from './agent-task';\n")
db_index = (ROOT / "packages/database/src/index.ts").read_text(encoding="utf-8")
if "./adapters/agent-task-repository" not in db_index:
    write(
        "packages/database/src/index.ts",
        db_index + "export * from './adapters/agent-task-repository';\n",
    )
foundation_test = (ROOT / "packages/database/src/database.integration.test.ts").read_text(encoding="utf-8")
foundation_test = foundation_test.replace("toHaveLength(2)", "toHaveLength(3)")
foundation_test = foundation_test.replace(
    "expect(status.applied).toHaveLength(1);\n    expect(status.pending).toEqual(['20260731140100000_add_seed_manifest']);",
    "expect(status.applied).toHaveLength(2);\n    expect(status.pending).toEqual(['20260731140200000_add_agent_tasks']);",
)
write("packages/database/src/database.integration.test.ts", foundation_test)

# NestJS presentation and composition adapters.
write(
    "apps/api/src/app/agent-tasks/agent-tasks.controller.ts",
    r'''
    import {
      AgentTaskForbiddenError,
      AgentTaskNotFoundError,
      AgentTaskValidationError,
      CreateAgentTask,
      GetAgentTask,
      type AgentTask,
    } from '@agentic-webapp/backend-agent-task';
    import type {
      AgentTaskResponse,
      CreateAgentTaskRequest,
      CreateAgentTaskSuccessResponse,
      GetAgentTaskSuccessResponse,
    } from '@agentic-webapp/contracts/server';
    import {
      BadRequestException,
      Body,
      Controller,
      ForbiddenException,
      Get,
      Headers,
      HttpCode,
      HttpStatus,
      NotFoundException,
      Param,
      Post,
    } from '@nestjs/common';

    function toResponse(task: AgentTask): AgentTaskResponse {
      return {
        id: task.id,
        title: task.title,
        prompt: task.prompt,
        status: task.status,
        correlationId: task.correlationId,
        createdAt: task.createdAt.toISOString(),
      };
    }

    function requireActor(actorId: string | undefined): string {
      if (!actorId?.trim()) {
        throw new BadRequestException({
          code: 'actor_required',
          message: 'x-actor-id is required.',
        });
      }
      return actorId.trim();
    }

    @Controller('agent-tasks')
    export class AgentTasksController {
      public constructor(
        private readonly createAgentTask: CreateAgentTask,
        private readonly getAgentTask: GetAgentTask,
      ) {}

      @Post()
      @HttpCode(HttpStatus.CREATED)
      public async create(
        @Body() body: CreateAgentTaskRequest,
        @Headers('x-actor-id') actorHeader?: string,
        @Headers('x-correlation-id') correlationId?: string,
      ): Promise<CreateAgentTaskSuccessResponse> {
        try {
          const task = await this.createAgentTask.execute({
            actorId: requireActor(actorHeader),
            title: body.title,
            prompt: body.prompt,
            correlationId: correlationId?.trim() || undefined,
          });
          return toResponse(task);
        } catch (error) {
          if (error instanceof AgentTaskValidationError) {
            throw new BadRequestException({
              code: 'validation_failed',
              message: error.message,
            });
          }
          throw error;
        }
      }

      @Get(':taskId')
      public async get(
        @Param('taskId') taskId: string,
        @Headers('x-actor-id') actorHeader?: string,
      ): Promise<GetAgentTaskSuccessResponse> {
        try {
          return toResponse(
            await this.getAgentTask.execute(taskId, requireActor(actorHeader)),
          );
        } catch (error) {
          if (error instanceof AgentTaskNotFoundError) {
            throw new NotFoundException({ code: 'not_found', message: error.message });
          }
          if (error instanceof AgentTaskForbiddenError) {
            throw new ForbiddenException({ code: 'forbidden', message: error.message });
          }
          throw error;
        }
      }
    }
    ''',
)
write(
    "apps/api/src/app/agent-tasks/agent-tasks.module.ts",
    r'''
    import {
      AGENT_TASK_REPOSITORY,
      CreateAgentTask,
      GetAgentTask,
      type AgentTaskRepository,
    } from '@agentic-webapp/backend-agent-task';
    import {
      createDatabase,
      DrizzleAgentTaskRepository,
      type DatabaseConnection,
    } from '@agentic-webapp/database';
    import { Inject, Injectable, Module, OnModuleDestroy } from '@nestjs/common';

    import { AgentTasksController } from './agent-tasks.controller';

    @Injectable()
    class ApiDatabaseConnection implements OnModuleDestroy {
      public readonly value: DatabaseConnection = createDatabase({
        connectionString:
          process.env.DATABASE_URL ??
          'postgresql://postgres:postgres@localhost:5432/agentic_webapp',
        applicationName: 'agentic-webapp-api',
      });

      public async onModuleDestroy(): Promise<void> {
        await this.value.close();
      }
    }

    @Injectable()
    class RepositoryProvider {
      public readonly value: AgentTaskRepository;

      public constructor(connection: ApiDatabaseConnection) {
        this.value = new DrizzleAgentTaskRepository(connection.value.database);
      }
    }

    @Injectable()
    class CreateAgentTaskProvider extends CreateAgentTask {
      public constructor(
        @Inject(AGENT_TASK_REPOSITORY) repository: AgentTaskRepository,
      ) {
        super(repository);
      }
    }

    @Injectable()
    class GetAgentTaskProvider extends GetAgentTask {
      public constructor(
        @Inject(AGENT_TASK_REPOSITORY) repository: AgentTaskRepository,
      ) {
        super(repository);
      }
    }

    @Module({
      controllers: [AgentTasksController],
      providers: [
        ApiDatabaseConnection,
        RepositoryProvider,
        {
          provide: AGENT_TASK_REPOSITORY,
          inject: [RepositoryProvider],
          useFactory: (provider: RepositoryProvider) => provider.value,
        },
        { provide: CreateAgentTask, useClass: CreateAgentTaskProvider },
        { provide: GetAgentTask, useClass: GetAgentTaskProvider },
      ],
    })
    export class AgentTasksModule {}
    ''',
)
write(
    "apps/api/src/app/agent-tasks/agent-tasks.controller.spec.ts",
    r'''
    import { CreateAgentTask, GetAgentTask } from '@agentic-webapp/backend-agent-task';
    import { describe, expect, it, vi } from 'vitest';

    import { AgentTasksController } from './agent-tasks.controller';

    describe('AgentTasksController', () => {
      it('maps the actor and correlation headers into the use case', async () => {
        const repository = { create: vi.fn(), findById: vi.fn() };
        const create = new CreateAgentTask(repository, {
          createId: () => '11111111-1111-4111-8111-111111111111',
          now: () => new Date('2026-07-31T17:00:00.000Z'),
        });
        const controller = new AgentTasksController(create, new GetAgentTask(repository));

        const result = await controller.create(
          { title: 'Task', prompt: 'Prompt' },
          'actor-1',
          'trace-1',
        );

        expect(result).toMatchObject({ correlationId: 'trace-1', status: 'queued' });
        expect(repository.create).toHaveBeenCalledWith(
          expect.objectContaining({ ownerId: 'actor-1' }),
          expect.objectContaining({ correlationId: 'trace-1' }),
        );
      });
    });
    ''',
)
write(
    "apps/api/src/app/app.module.ts",
    r'''
    import { Module } from '@nestjs/common';

    import { AgentTasksModule } from './agent-tasks/agent-tasks.module';
    import { AppController } from './app.controller';
    import { AppService } from './app.service';

    @Module({
      imports: [AgentTasksModule],
      controllers: [AppController],
      providers: [AppService],
    })
    export class AppModule {}
    ''',
)

# Worker job uses the generated shared event contract and preserves correlation.
write(
    "apps/worker/src/jobs/execute-agent-task/contract.ts",
    r'''
    import type { AgentTaskExecutionRequested } from '@agentic-webapp/contracts';

    export { agentTaskExecutionRequestedSchema } from '@agentic-webapp/contracts';
    export type ExecuteAgentTaskJobPayload = AgentTaskExecutionRequested;

    export const executeAgentTaskQueue = 'agent-tasks' as const;

    export interface ExecuteAgentTaskJobResult {
      readonly taskId: string;
      readonly correlationId: string;
      readonly completedAt: string;
    }
    ''',
)
write(
    "apps/worker/src/jobs/execute-agent-task/handler.ts",
    r'''
    import {
      agentTaskExecutionRequestedSchema,
      type ExecuteAgentTaskJobPayload,
      type ExecuteAgentTaskJobResult,
    } from './contract';

    export async function handleExecuteAgentTaskJob(
      payload: ExecuteAgentTaskJobPayload,
    ): Promise<ExecuteAgentTaskJobResult> {
      const validated = agentTaskExecutionRequestedSchema.parse(payload);
      return {
        taskId: validated.taskId,
        correlationId: validated.correlationId,
        completedAt: new Date().toISOString(),
      };
    }
    ''',
)
write(
    "apps/worker/src/jobs/execute-agent-task/handler.spec.ts",
    r'''
    import { describe, expect, it } from 'vitest';

    import { handleExecuteAgentTaskJob } from './handler';

    describe('handleExecuteAgentTaskJob', () => {
      it('preserves the browser-to-worker correlation identifier', async () => {
        const result = await handleExecuteAgentTaskJob({
          version: 1,
          taskId: '11111111-1111-4111-8111-111111111111',
          actorId: 'actor-1',
          prompt: 'Prompt',
          correlationId: 'trace-1',
          occurredAt: '2026-07-31T17:00:00.000Z',
        });
        expect(result).toMatchObject({
          taskId: '11111111-1111-4111-8111-111111111111',
          correlationId: 'trace-1',
        });
      });
    });
    ''',
)

# Browser feature and route.
write(
    "packages/web/features/agent-tasks/src/lib/agent-tasks-model.ts",
    r'''
    export interface AgentTaskDraft {
      readonly title: string;
      readonly prompt: string;
    }

    export interface AgentTaskFeatureState {
      readonly status: 'idle' | 'submitting' | 'success' | 'error';
      readonly message: string;
    }

    export function validateAgentTaskDraft(draft: AgentTaskDraft): string[] {
      const issues: string[] = [];
      if (!draft.title.trim()) issues.push('Title is required.');
      if (draft.title.trim().length > 120) issues.push('Title is too long.');
      if (!draft.prompt.trim()) issues.push('Prompt is required.');
      if (draft.prompt.trim().length > 4000) issues.push('Prompt is too long.');
      return issues;
    }
    ''',
)
write(
    "packages/web/features/agent-tasks/src/lib/agent-tasks-model.spec.ts",
    r'''
    import { describe, expect, it } from 'vitest';

    import { validateAgentTaskDraft } from './agent-tasks-model';

    describe('validateAgentTaskDraft', () => {
      it('reports accessible client-side validation issues', () => {
        expect(validateAgentTaskDraft({ title: '', prompt: '  ' })).toEqual([
          'Title is required.',
          'Prompt is required.',
        ]);
      });
    });
    ''',
)
write(
    "packages/web/features/agent-tasks/src/lib/agent-tasks-feature.tsx",
    r'''
    'use client';

    import { createApiClient } from '@agentic-webapp/contracts/client';
    import { type FormEvent, useMemo, useState } from 'react';

    import {
      type AgentTaskFeatureState,
      validateAgentTaskDraft,
    } from './agent-tasks-model';

    const defaultActorId = '00000000-0000-4000-8000-000000000001';

    export function AgentTasksFeature() {
      const client = useMemo(
        () =>
          createApiClient({
            baseUrl: process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:4000',
          }),
        [],
      );
      const [actorId, setActorId] = useState(defaultActorId);
      const [title, setTitle] = useState('');
      const [prompt, setPrompt] = useState('');
      const [taskId, setTaskId] = useState('');
      const [state, setState] = useState<AgentTaskFeatureState>({
        status: 'idle',
        message: 'Create a task to queue an agent workflow.',
      });

      async function createTask(event: FormEvent<HTMLFormElement>) {
        event.preventDefault();
        const issues = validateAgentTaskDraft({ title, prompt });
        if (issues.length > 0) {
          setState({ status: 'error', message: issues.join(' ') });
          return;
        }

        setState({ status: 'submitting', message: 'Queuing the agent task…' });
        const correlationId = crypto.randomUUID();
        try {
          const task = await client.createAgentTask({
            headers: {
              'x-actor-id': actorId,
              'x-correlation-id': correlationId,
            },
            body: { title, prompt },
          });
          setTaskId(task.id);
          setState({
            status: 'success',
            message: `Queued ${task.title} with correlation ${task.correlationId}.`,
          });
        } catch (error: unknown) {
          setState({
            status: 'error',
            message: error instanceof Error ? error.message : 'Task creation failed.',
          });
        }
      }

      async function readTask() {
        if (!taskId.trim()) {
          setState({ status: 'error', message: 'Enter a task identifier.' });
          return;
        }
        setState({ status: 'submitting', message: 'Loading the owned task…' });
        try {
          const task = await client.getAgentTask({
            path: { taskId: taskId.trim() },
            headers: { 'x-actor-id': actorId },
          });
          setState({
            status: 'success',
            message: `${task.title} is ${task.status} (${task.correlationId}).`,
          });
        } catch (error: unknown) {
          setState({
            status: 'error',
            message: error instanceof Error ? error.message : 'Task lookup failed.',
          });
        }
      }

      return (
        <section aria-labelledby="agent-tasks-heading">
          <h1 id="agent-tasks-heading">Agent tasks</h1>
          <p>
            This reference workflow validates input, persists an actor-owned task,
            writes a correlated execution request to the outbox, and exposes the
            generated client to the browser.
          </p>

          <form onSubmit={createTask}>
            <label>
              Development actor
              <input
                name="actorId"
                value={actorId}
                onChange={(event) => setActorId(event.target.value)}
                required
              />
            </label>
            <label>
              Task title
              <input
                name="title"
                value={title}
                onChange={(event) => setTitle(event.target.value)}
                maxLength={120}
                required
              />
            </label>
            <label>
              Agent prompt
              <textarea
                name="prompt"
                value={prompt}
                onChange={(event) => setPrompt(event.target.value)}
                maxLength={4000}
                required
              />
            </label>
            <button type="submit" disabled={state.status === 'submitting'}>
              Create task
            </button>
          </form>

          <div>
            <label>
              Task identifier
              <input
                name="taskId"
                value={taskId}
                onChange={(event) => setTaskId(event.target.value)}
              />
            </label>
            <button type="button" onClick={() => void readTask()}>
              Read owned task
            </button>
          </div>

          <p role="status" aria-live="polite" data-status={state.status}>
            {state.message}
          </p>
        </section>
      );
    }
    ''',
)
write(
    "packages/web/features/agent-tasks/src/index.ts",
    r'''
    export * from './lib/agent-tasks-feature';
    export * from './lib/agent-tasks-model';
    ''',
)
write(
    "apps/web/src/app/agent-tasks/page.tsx",
    r'''
    import { AgentTasksFeature } from '@agentic-webapp/web-feature-agent-tasks';

    export default function AgentTasksPage() {
      return (
        <main>
          <AgentTasksFeature />
        </main>
      );
    }
    ''',
)
page = (ROOT / "apps/web/src/app/page.tsx").read_text(encoding="utf-8")
page = page.replace(
    "      <ApiHealth />",
    "      <ApiHealth />\n      <p><a href=\"/agent-tasks\">Open the Agent Tasks reference feature</a></p>",
)
write("apps/web/src/app/page.tsx", page)

write(
    "packages/web/features/agent-tasks/playwright.config.ts",
    r'''
    import { defineConfig } from '@playwright/test';

    export default defineConfig({
      testDir: './e2e',
      use: { baseURL: 'http://127.0.0.1:3000' },
      webServer: {
        command: 'pnpm nx dev web',
        url: 'http://127.0.0.1:3000/agent-tasks',
        reuseExistingServer: !process.env.CI,
        timeout: 120_000,
      },
    });
    ''',
)
write(
    "packages/web/features/agent-tasks/e2e/agent-tasks.spec.ts",
    r'''
    import { expect, test } from '@playwright/test';

    test('creates a correlated task through the generated browser client', async ({
      page,
    }) => {
      const taskId = '11111111-1111-4111-8111-111111111111';
      await page.route('http://localhost:4000/api/agent-tasks', async (route) => {
        const request = route.request();
        expect(request.method()).toBe('POST');
        expect(request.headers()['x-actor-id']).toBe(
          '00000000-0000-4000-8000-000000000001',
        );
        const body = request.postDataJSON() as { title: string; prompt: string };
        expect(body).toEqual({
          title: 'Summarize feedback',
          prompt: 'Group feedback into themes.',
        });
        await route.fulfill({
          status: 201,
          contentType: 'application/json',
          body: JSON.stringify({
            id: taskId,
            title: body.title,
            prompt: body.prompt,
            status: 'queued',
            correlationId: request.headers()['x-correlation-id'],
            createdAt: '2026-07-31T17:00:00.000Z',
          }),
        });
      });

      await page.goto('/agent-tasks');
      await page.getByLabel('Task title').fill('Summarize feedback');
      await page.getByLabel('Agent prompt').fill('Group feedback into themes.');
      await page.getByRole('button', { name: 'Create task' }).click();

      await expect(page.getByRole('status')).toContainText('Queued Summarize feedback');
      await expect(page.getByLabel('Task identifier')).toHaveValue(taskId);
    });
    ''',
)

# Package dependencies and Nx e2e target.
def add_dependency(path: str, name: str, version: str = "workspace:*") -> None:
    package = read_json(path)
    dependencies = package.setdefault("dependencies", {})
    dependencies[name] = version
    package["dependencies"] = dict(sorted(dependencies.items()))
    write_json(path, package)

add_dependency("packages/backend/agent-task/package.json", "@agentic-webapp/contracts")
add_dependency("packages/database/package.json", "@agentic-webapp/backend-agent-task")
add_dependency("packages/database/package.json", "@agentic-webapp/contracts")
add_dependency("apps/api/package.json", "@agentic-webapp/backend-agent-task")
add_dependency("apps/api/package.json", "@agentic-webapp/database")
add_dependency("apps/web/package.json", "@agentic-webapp/web-feature-agent-tasks")
add_dependency("packages/web/features/agent-tasks/package.json", "@agentic-webapp/contracts")

feature_project = read_json("packages/web/features/agent-tasks/project.json")
feature_project.setdefault("targets", {})["e2e"] = {
    "executor": "nx:run-commands",
    "options": {
        "command": "playwright test -c packages/web/features/agent-tasks/playwright.config.ts"
    },
}
write_json("packages/web/features/agent-tasks/project.json", feature_project)

# Enforce P5-07 without banning legitimate view-model types.
eslint = (ROOT / "eslint.config.mjs").read_text(encoding="utf-8")
insert = r'''
  {
    files: ['packages/web/features/**/*.{ts,tsx}'],
    ignores: ['**/*.spec.ts', '**/*.config.ts'],
    rules: {
      'no-restricted-syntax': [
        'error',
        {
          selector:
            'TSInterfaceDeclaration[id.name=/.*(Request|Response|Dto)$/]',
          message:
            'Web features must consume generated API types instead of handwritten request/response/DTO interfaces.',
        },
        {
          selector: 'TSTypeAliasDeclaration[id.name=/.*(Request|Response|Dto)$/]',
          message:
            'Web features must consume generated API types instead of handwritten request/response/DTO aliases.',
        },
      ],
    },
  },
'''
eslint = eslint.replace("  {\n    files: ['**/*.ts'", insert + "  {\n    files: ['**/*.ts'", 1)
write("eslint.config.mjs", eslint)

# Permanent CI coverage for Playwright.
ci = (ROOT / ".github/workflows/ci.yml").read_text(encoding="utf-8")
ci = ci.replace(
    "      - run: pnpm build\n",
    "      - run: pnpm build\n      - run: pnpm exec playwright install --with-deps chromium\n      - run: pnpm nx affected -t e2e --parallel=1\n",
)
write(".github/workflows/ci.yml", ci)

# Maintained execution ledger and canonical guide.
todo = (ROOT / "docs/TODO.md").read_text(encoding="utf-8")
todo = todo.replace("- [ ] **P4-06**", "- [x] **P4-06**")
todo = todo.replace("- [ ] **P5-07**", "- [x] **P5-07**")
for task in range(1, 9):
    todo = todo.replace(f"- [ ] **P6-{task:02d}**", f"- [x] **P6-{task:02d}**")
todo = todo.replace(
    "PR #4 completes the shared database platform. P4-06 remains sequenced after the reference domain is selected so adapters implement a real domain port rather than a placeholder abstraction.",
    "PR #4 established the shared database platform. Phase 6 closes P4-06 with the real Agent Task repository and transactional job-outbox adapter.",
)
todo = todo.replace(
    "PR #5 completes the Phase 5 contract foundation and proves generated server/browser consumption through the health operation. P5-07 remains planned for executable duplicate-type enforcement as feature contracts expand.",
    "PR #5 established the contract foundation. Phase 6 closes P5-07 with executable lint enforcement in browser feature projects and generated-client consumption in the Agent Tasks feature.",
)
write("docs/TODO.md", todo)

write(
    "docs/reference-feature-agent-tasks.md",
    r'''
    # Agent Tasks reference feature

    Agent Tasks is the canonical vertical example for contributors and coding agents. It demonstrates the expected dependency direction from a Next.js route through a browser feature and generated client, into NestJS presentation adapters, framework-free application/domain code, a Drizzle repository, PostgreSQL, and a versioned worker event.

    ## Workflow

    1. The browser creates a correlation identifier and calls the generated `createAgentTask` client method.
    2. The API reads the temporary `x-actor-id` request-context adapter. Phase 8 replaces this adapter with authenticated identity without changing the application use cases.
    3. `CreateAgentTask` validates and normalizes the command, creates the domain entity, and produces the generated `AgentTaskExecutionRequested` contract.
    4. `DrizzleAgentTaskRepository` writes the task and outbox event in one transaction.
    5. The worker handler validates the same versioned contract and preserves the correlation identifier.
    6. Actor-scoped reads are authorized by the application use case before the API returns data.

    ## Where changes belong

    - OpenAPI request/response changes: `packages/contracts/openapi/source`
    - Runtime event changes: `packages/contracts/src/agent-task-execution-requested`
    - Invariants and use cases: `packages/backend/agent-task`
    - PostgreSQL schema and adapters: `packages/database`
    - HTTP composition: `apps/api/src/app/agent-tasks`
    - Browser states: `packages/web/features/agent-tasks`
    - Route composition only: `apps/web/src/app/agent-tasks`
    - Worker transport-independent behavior: `apps/worker/src/jobs/execute-agent-task`

    ## Validation map

    - Domain unit tests cover normalization, validation, persistence calls, and authorization.
    - Contract tests cover the event schema and generated HTTP drift/compatibility.
    - PostgreSQL Testcontainers tests cover migrations, the repository, and the transactional outbox.
    - API unit tests cover header-to-command mapping.
    - Playwright covers browser states and the generated client request shape.
    - The generated-output smoke test ensures the source generators remain usable after this example evolves.
    ''',
)
